-- Tabela de fluxo de caixa mensal (Provou Levou). Rodar no SQL Editor do Supabase.
-- Alimentada ao fechar cada mês: exportar "Extrato de conta" (CSV) do Mercado Pago,
-- categorizar (ver skill fluxo-caixa-provou-levou) e inserir o resumo aqui.
CREATE TABLE IF NOT EXISTS public.fluxo_caixa_mensal (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    mes                text UNIQUE NOT NULL,        -- 'YYYY-MM'
    fechado            boolean DEFAULT false,       -- mês fechado (dados completos)?
    receita_bruta      numeric DEFAULT 0,
    receita_liquida    numeric DEFAULT 0,           -- bruta - reembolsos
    custo_provas       numeric DEFAULT 0,           -- Google (óculos R$0,28 / roupa R$0,37)
    custo_ferramentas  numeric DEFAULT 0,           -- Anthropic, Hostinger, Uazapi, Magnific, ads
    tarifas            numeric DEFAULT 0,           -- tarifas MP + IOF
    lucro_negocio      numeric DEFAULT 0,           -- receita_liq - provas - ferramentas - tarifas
    gastos_pessoais    numeric DEFAULT 0,           -- aluguel, comida, roupa, etc. (uso do lucro)
    retiradas          numeric DEFAULT 0,           -- pró-labore (Pix Lucas) + terceiros
    saldo_final        numeric DEFAULT 0,
    categorias         jsonb DEFAULT '{}'::jsonb,   -- {categoria: valor} detalhado
    obs                text,
    updated_at         timestamptz DEFAULT now()
);

INSERT INTO public.fluxo_caixa_mensal
 (mes, fechado, receita_bruta, receita_liquida, custo_provas, custo_ferramentas, tarifas, lucro_negocio, gastos_pessoais, retiradas, saldo_final, categorias, obs)
VALUES
 ('2026-06', true, 34140.57, 34140.57, 9968.76, 1616.82, 86.03, 22468.96, 1154.56, 21835.15, 48.35,
  '{"provas":9968.76,"ferramentas":1176.82,"anuncios":440.00,"tarifas":86.03,"retirada_lucas":14699.48,"pix_terceiros":7135.67,"pessoal_outros":1154.56}'::jsonb,
  'Mês fechado. Lucro quase todo distribuído (retiradas), saldo final R$48.'),
 ('2026-07', false, 30484.86, 28284.86, 10278.00, 1316.84, 329.52, 16360.50, 5995.00, 0.00, 10984.36,
  '{"provas":10278.00,"ferramentas":1316.84,"tarifas":329.52,"reembolso":2200.00,"aluguel":2123.14,"compras_pessoais":720.00,"alimentacao":2837.00,"pix_terceiros":315.00}'::jsonb,
  'Parcial (1-15/07). Lucas nao fez retirada formal; paga pessoal direto da conta -> saldo acumulou.')
ON CONFLICT (mes) DO UPDATE SET
  fechado=EXCLUDED.fechado, receita_bruta=EXCLUDED.receita_bruta, receita_liquida=EXCLUDED.receita_liquida,
  custo_provas=EXCLUDED.custo_provas, custo_ferramentas=EXCLUDED.custo_ferramentas, tarifas=EXCLUDED.tarifas,
  lucro_negocio=EXCLUDED.lucro_negocio, gastos_pessoais=EXCLUDED.gastos_pessoais, retiradas=EXCLUDED.retiradas,
  saldo_final=EXCLUDED.saldo_final, categorias=EXCLUDED.categorias, obs=EXCLUDED.obs, updated_at=now();
